port: 6667
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
baseurl: /design
sass:
  load_paths:
    - assets/_scss
    - assets/_scss_new
    - node_modules
  style: compressed